### ISSUE TITLE
Add a Scripting Define Symbol which shows the presence of Zenject in project

### ISSUE THREAD

**Issue by pnarimani** [Mathijs-Bakker/Extenject#10]
**Is your feature request related to a problem? Please describe.**
It is impossible for other plugin developers to know if the project uses Zenject or not. It forces other libraries to have their own dependency management system.

**Describe the solution you'd like**
If we add a Scripting Define Symbol such as `ZENJECT_9` to the Unity project, other plugin developers can check for this symbol and change their dependency management and instantiation to work with Zenject.

**Describe alternatives you've considered**
It's also possible to do this with the new package manager. If all plugins are provided via Unity's Package Manager, it is possible to add symbols when a particular package is present.

**Additional context**
Odin Inspector also does this too. In project which Odin Inspector is present, symbol `ODIN_INSPECTOR` is defined. That way, other plugin developers can use Odin features only when user has Odin.

**Comment by Mathijs-Bakker** [comment]
This feat is going to be implemented in the upcoming UPM branch. 
 I will close this for now.
