### ISSUE TITLE
RuntimeInitializeOnLoadMethodAttribute is not allowed on Generic classes

### ISSUE THREAD

**Issue by daltonbr** [Mathijs-Bakker/Extenject#24]
**Describe the bug**

When building a project with Extenject I got three similar errors related to those classes `HashSetPool`, `DictionaryPool`, `ListPool`.

```
RuntimeInitializeOnLoadMethodAttribute: Is not allowed on a Generic class DictionaryPool`2.ResetStaticValues
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

**To Reproduce**

1. Download the [sample project](https://drive.google.com/file/d/1wNCEpfWU28UOV1R5qCpEtcmyH90A9SHM/view?usp=sharing)
2. Try to build the app for iOS, Android, or Desktop.
3. Check the three errors in Console.

**Expected behavior**
The app should build without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/10944679/151675637-2d3d6c45-0a73-4fa1-8e14-7871fef4d6b9.png)

**Extenject and Unity info**
 - Extenject version: **9.3.0**
 - Unity version: **2021.2.7f1** and **2021.2.9f1**
 - Project's scripting backend - The errors happen regardless of  **Mono** or **IL2CPP**.
 - Tested only on MacOS Monterey 12.2

**Additional context**

* The problem seems to be introduced in this [PR](https://github.com/Mathijs-Bakker/Extenject/pull/6)
* Those three generic classes are using that attribute [RuntimeInitializeOnLoadMethodAttribute](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html) on methods (e.g. `HashSetPool`.`ResetStaticValues()`) that seems that they are never called. From what I understood they should be called when you Press play in the Unity Editor for instance.
    * I've tried to put a **breakPoint** or a **dummy Debug.Log** message and press Play in Unity Editor, but those methods are never called.  Regardless of `EnterPlayModeSettings` or `ReloadDomain` are enabled or not. (`Edit` -> `Project Settings` -> `Editor`)
    * Similar methods in non-generic classes are called as expected (e.g. `ProjectContext`.`ResetStaticValues()`)
* Removing those three methods `ResetStaticValues()` in the three classes seems to solve the problem, still I am not sure if that would break the fix that the aforementioned [PR](https://github.com/Mathijs-Bakker/Extenject/pull/6) tried to solve.

**Comment by Mathijs-Bakker** [comment]
Merged

**Comment by wewrere41** [comment]
Same errors on 9.3.0
2021.3.0

**Comment by lordmortis** [comment]
Yeah, this is definitely back in 9.3.0 on 2021.3.4f1

**Comment by starock** [comment]
Zenject 9.2.1 , Unity2021.3.10f1  building WebGL, same issue.
