### ISSUE TITLE
Allow to use closures for factories

### ISSUE THREAD

**Issue by floriansimon1** [Mathijs-Bakker/Extenject#54]
Instead of forcing to create a new class, it would be great if Exenject allowed to pass a closure that takes a DiContainer as input and returns a function that represents the factory.

I might submit a PR for this.

**Comment by Mathijs-Bakker** [comment]
That's actually a nice idea.
Think I like it!

**Comment by floriansimon1** [comment]
I tried it, and the code base was a bit too difficult to understand for me with the limited time I had. I might revisit this later, but I don't think I'd be able to quickly come up with something to implement this.

Apologies for the inconvenience!
