### ISSUE TITLE
Missing Create -> Zenject -> Reflection Baking Settings

### ISSUE THREAD

**Issue by joaokucera** [Mathijs-Bakker/Extenject#58]
**Describe the bug**
Missing "Create -> Zenject -> Reflection Baking Settings" option.

**To Reproduce**
Try to create a Reflection Baking Settings asset but there is no option for it.

**Expected behavior**
A way to create a Reflection Baking Settings asset.

**Screenshots**
![projecttab](https://user-images.githubusercontent.com/933529/197555773-5a1c13f5-5235-4c1d-bff7-9afa83c4a08c.png)
![assets](https://user-images.githubusercontent.com/933529/197555778-c751007f-fd55-43e1-b897-16ef51bd96f1.png)

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.2.0
 - Unity version: 2021.3.1f
 - Project's scripting backend [e.g. Mono/IL2CPP]: IL2CPP

**Additional context**
I wonder if it is possible to create a Reflection Baking Settings asset in another way.

**Comment by Mathijs-Bakker** [comment]
I just created a new project in **Unity 2021.3** and installed **Extenject 9.2.0** from the [release page](https://github.com/Mathijs-Bakker/Extenject/releases)

And the  ``Reflection Baking Settings`` option is just there.

_Note:_
When you install Extenject from the _Unity Asset Store_, you need to extract **Reflection Baking** from the ``Optional Extras`` folder.

**Comment by joaokucera** [comment]
I have forked https://github.com/Mathijs-Bakker/Extenject and created a NPM package from it.
I guess `Optional Extras` folder wasnt included. I will have a look and will tell u soon.

**Comment by Mathijs-Bakker** [comment]
The Unity Asset Store (UAS) package has always been created differently.
As the UAS has its own take about distribution.

To offer a minimal installation of Zenject, the demos, reflection baking and other add-ons where zipped into the Optional Extras folder. 
And have to be unzipped and installed manually.

**Comment by joaokucera** [comment]
Hello, I am trying to update my zenject version to your latest tag:
https://github.com/Mathijs-Bakker/Extenject/compare/9.2.0...Mathijs-Bakker:Extenject:9.3.1
however, there are 1879 file changes. Is it correct?
