### ISSUE TITLE
Reflection Baking doesn't work

### ISSUE THREAD

**Issue by pnarimani** [Mathijs-Bakker/Extenject#7]
**Describe the bug**
I have ZenjectReflectionBakingSettings object in my project but reflection baking doesn't work.

**To Reproduce**
I have a sample project uploaded on github:
https://github.com/mnarimani/ExtenjectReflectionBakingBug

Build the project and run. I have included InGameConsole package so you can see warnings in the build. 
When you run the built executable, you will see that there will be some warnings which say some types don't have reflection baking info (Including my own types which are UserA, UserB and User C). 

**Expected behavior**
All of my types (and probably Zenject's types) should have reflection baking info.

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.0.2
 - Unity version: 2021.1.3
 - Project's scripting backend: Mono

**Comment by pnarimani** [comment]
I think I found a couple of places that produce problems.

First, here Zenject namespace gets added to the `_namespaceRegexes`:
https://github.com/Mathijs-Bakker/Extenject/blob/42e7bd9b4efcb0e67bee98c0ccfff87e31471b54/UnityProject/Assets/Plugins/Zenject/OptionalExtras/ReflectionBaking/Common/ReflectionBakingModuleEditor.cs#L44

and then here `_namespaceRegexes` gets checked for emptiness:
https://github.com/Mathijs-Bakker/Extenject/blob/42e7bd9b4efcb0e67bee98c0ccfff87e31471b54/UnityProject/Assets/Plugins/Zenject/OptionalExtras/ReflectionBaking/Common/ReflectionBakingModuleEditor.cs#L69

Second, I think Unity changed the directory which it puts the player assemblies. 
When you call `AssemblyPathRegistry.GetAllGeneratedAssemblyRelativePaths()` here:
https://github.com/Mathijs-Bakker/Extenject/blob/42e7bd9b4efcb0e67bee98c0ccfff87e31471b54/UnityProject/Assets/Plugins/Zenject/OptionalExtras/ReflectionBaking/Unity/ZenjectReflectionBakingSettingsEditor.cs#L194

My assembly (which is compiled from an assembly definition file named "Code") gets returned as:
```
Library\ScriptAssemblies\Code.dll
```

But here when we receive callback for assembly when we build:
https://github.com/Mathijs-Bakker/Extenject/blob/42e7bd9b4efcb0e67bee98c0ccfff87e31471b54/UnityProject/Assets/Plugins/Zenject/OptionalExtras/ReflectionBaking/Unity/ReflectionBakingBuildObserver.cs#L41

parameter `assemblyAssetPath` has the value of:
```
Library/PlayerScriptAssemblies/Code.dll
```

and it is needless to say this assembly doesn't get weaved because of this.

I will try to solve these two issues in a PR.

**Comment by Mathijs-Bakker** [comment]
Merged!
And Thanks!
